// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyHDX8U8Sw3YycfKHC1V3V9qtZQCITDnc',
    appId: '1:264728536491:web:293536a98a07c6b7461eee',
    messagingSenderId: '264728536491',
    projectId: 'skilltrackit',
    authDomain: 'skilltrackit.firebaseapp.com',
    storageBucket: 'skilltrackit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjZoxLwuMV6kF26IOIPNJacGHJCTTuXzM',
    appId: '1:264728536491:android:a4bbe8fe9a64a5c7461eee',
    messagingSenderId: '264728536491',
    projectId: 'skilltrackit',
    storageBucket: 'skilltrackit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADc0AdYXbfxGCEyy1aAfNaf7sxcWPt3tw',
    appId: '1:264728536491:ios:d0e93b3b02f9d03f461eee',
    messagingSenderId: '264728536491',
    projectId: 'skilltrackit',
    storageBucket: 'skilltrackit.firebasestorage.app',
    androidClientId: '264728536491-1vr0hcqoevduf32vmaprm1689vr8sc46.apps.googleusercontent.com',
    iosClientId: '264728536491-gvifpe5rvr1m3o4gbvh5iqub867michp.apps.googleusercontent.com',
    iosBundleId: 'com.example.skilltrackit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADc0AdYXbfxGCEyy1aAfNaf7sxcWPt3tw',
    appId: '1:264728536491:ios:d0e93b3b02f9d03f461eee',
    messagingSenderId: '264728536491',
    projectId: 'skilltrackit',
    storageBucket: 'skilltrackit.firebasestorage.app',
    androidClientId: '264728536491-1vr0hcqoevduf32vmaprm1689vr8sc46.apps.googleusercontent.com',
    iosClientId: '264728536491-gvifpe5rvr1m3o4gbvh5iqub867michp.apps.googleusercontent.com',
    iosBundleId: 'com.example.skilltrackit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyHDX8U8Sw3YycfKHC1V3V9qtZQCITDnc',
    appId: '1:264728536491:web:6904d7acb447ee08461eee',
    messagingSenderId: '264728536491',
    projectId: 'skilltrackit',
    authDomain: 'skilltrackit.firebaseapp.com',
    storageBucket: 'skilltrackit.firebasestorage.app',
  );
}
